import type { Meta, StoryObj } from "@storybook/react";
import { Card, CardHeader, CardBody, CardFooter, Button, Badge } from "@ai-ds/components";

const meta = {
  title: "Components/Card",
  component: Card,
  parameters: { layout: "centered" },
  tags: ["autodocs"],
  decorators: [(Story) => <div style={{ width: "360px" }}><Story /></div>],
} satisfies Meta<typeof Card>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  render: () => (
    <Card>
      <CardHeader>
        <p style={{ margin: 0, fontWeight: 600 }}>Card title</p>
      </CardHeader>
      <CardBody>
        <p style={{ margin: 0, fontSize: "14px", color: "var(--color-foreground-subtle)" }}>
          Card content goes here. This is the main body of the card.
        </p>
      </CardBody>
      <CardFooter>
        <Button size="sm">Action</Button>
      </CardFooter>
    </Card>
  ),
};

export const AICard: Story = {
  render: () => (
    <Card variant="ai">
      <CardBody>
        <div style={{ display: "flex", flexDirection: "column", gap: "8px" }}>
          <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
            <Badge variant="ai">AI generated</Badge>
          </div>
          <p style={{ margin: 0, fontSize: "14px" }}>
            This content was generated by AI based on your input.
          </p>
        </div>
      </CardBody>
    </Card>
  ),
};

export const Elevated: Story = {
  render: () => (
    <Card variant="elevated">
      <CardBody>
        <p style={{ margin: 0 }}>Elevated card with shadow</p>
      </CardBody>
    </Card>
  ),
};
