/**
 * Generates CSS custom properties from design tokens.
 * Run: bun run scripts/build-css.ts
 */

import { writeFileSync, mkdirSync } from "fs";
import { tokens } from "../src/index";

function flattenObject(
  obj: Record<string, unknown>,
  prefix = "",
  separator = "-"
): Record<string, string> {
  return Object.entries(obj).reduce(
    (acc, [key, value]) => {
      const newKey = prefix ? `${prefix}${separator}${key}` : key;
      if (typeof value === "object" && value !== null && !Array.isArray(value)) {
        Object.assign(acc, flattenObject(value as Record<string, unknown>, newKey, separator));
      } else {
        acc[newKey] = String(value);
      }
      return acc;
    },
    {} as Record<string, string>
  );
}

function buildCSS(): string {
  const vars: string[] = [];

  // Colors
  const flatColors = flattenObject(tokens.colors as unknown as Record<string, unknown>, "color");
  for (const [key, value] of Object.entries(flatColors)) {
    vars.push(`  --${key}: ${value};`);
  }

  // Semantic colors
  const flatSemantic = flattenObject(
    tokens.semanticColors as unknown as Record<string, unknown>,
    "color"
  );
  for (const [key, value] of Object.entries(flatSemantic)) {
    vars.push(`  --${key}: ${value};`);
  }

  // Typography
  const flatFontSize = flattenObject(
    tokens.fontSize as unknown as Record<string, unknown>,
    "font-size"
  );
  for (const [key, value] of Object.entries(flatFontSize)) {
    vars.push(`  --${key}: ${value};`);
  }

  const flatFontWeight = flattenObject(
    tokens.fontWeight as unknown as Record<string, unknown>,
    "font-weight"
  );
  for (const [key, value] of Object.entries(flatFontWeight)) {
    vars.push(`  --${key}: ${value};`);
  }

  // Spacing
  const flatSpacing = flattenObject(
    tokens.spacing as unknown as Record<string, unknown>,
    "spacing"
  );
  for (const [key, value] of Object.entries(flatSpacing)) {
    vars.push(`  --${key}: ${value};`);
  }

  // Border radius
  const flatRadius = flattenObject(
    tokens.borderRadius as unknown as Record<string, unknown>,
    "radius"
  );
  for (const [key, value] of Object.entries(flatRadius)) {
    vars.push(`  --${key}: ${value};`);
  }

  // Shadows
  const flatShadows = flattenObject(
    tokens.shadows as unknown as Record<string, unknown>,
    "shadow"
  );
  for (const [key, value] of Object.entries(flatShadows)) {
    vars.push(`  --${key}: ${value};`);
  }

  return `/* Auto-generated by @ai-ds/tokens - DO NOT EDIT */\n:root {\n${vars.join("\n")}\n}\n`;
}

mkdirSync("./dist", { recursive: true });
const css = buildCSS();
writeFileSync("./dist/tokens.css", css);
console.log("✓ Generated dist/tokens.css");
